import { createHash } from 'node:crypto'
import {
    copyFileSync,
    existsSync,
    mkdirSync,
    readFileSync,
    renameSync,
    statSync,
    unlinkSync,
    writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { findMonorepoRoot, defaultHubPackageRoot } from './resolveUpgradeOffer'

export type ArtifactMeta = {
    version: string
    platform: string
    arch: string
    path: string
    sha256: string
    sizeBytes: number
}

const STUB_EMBEDDED_ASSETS = [
    '// This file is generated by hub fleet-upgrade artifact build (runner binary, no embedded web).',
    '// It intentionally contains no embedded assets.',
    '',
    'export interface EmbeddedWebAsset {',
    '    path: string;',
    '    sourcePath: string;',
    '    mimeType: string;',
    '}',
    '',
    'export const embeddedAssets: EmbeddedWebAsset[] = [];',
    '',
].join('\n')

function artifactsRoot(dataDir?: string): string {
    return join(dataDir ?? join(homedir(), '.hapi'), 'upgrade-artifacts')
}

export function artifactFileName(version: string, platform: string, arch: string): string {
    return `hapi-${version}-${platform}-${arch}`
}

export function readArtifactMeta(
    version: string,
    platform: string,
    arch: string,
    dataDir?: string,
): ArtifactMeta | null {
    const dir = artifactsRoot(dataDir)
    const path = join(dir, artifactFileName(version, platform, arch))
    const metaPath = `${path}.json`
    if (!existsSync(path) || !existsSync(metaPath)) {
        return null
    }
    try {
        return JSON.parse(readFileSync(metaPath, 'utf8')) as ArtifactMeta
    } catch {
        return null
    }
}

function writeMeta(meta: ArtifactMeta): void {
    writeFileSync(`${meta.path}.json`, JSON.stringify(meta, null, 2))
}

function featureFlagFor(platform: string, arch: string): string {
    const platformToken = platform === 'win32' ? 'WIN32' : platform.toUpperCase()
    return `HAPI_TARGET_${platformToken}_${arch.toUpperCase()}`
}

function bunCompileTarget(platform: string, arch: string): string {
    if (platform === 'linux' && arch === 'x64') {
        return 'bun-linux-x64-baseline'
    }
    if (platform === 'win32') {
        return `bun-windows-${arch}`
    }
    return `bun-${platform}-${arch}`
}

function tunwgBinaryPath(monorepoRoot: string, platform: string, arch: string): string {
    const name = platform === 'win32'
        ? `tunwg-${arch}-win32.exe`
        : `tunwg-${arch}-${platform === 'darwin' ? 'darwin' : 'linux'}`
    // win32 uses x64 only in practice
    const file = platform === 'win32' ? 'tunwg-x64-win32.exe' : name
    return join(monorepoRoot, 'shared', 'tools', 'tunwg', file)
}

async function ensureTunwgBinary(
    monorepoRoot: string,
    platform: string,
    arch: string,
    bunCommand: string,
): Promise<void> {
    const path = tunwgBinaryPath(monorepoRoot, platform, arch)
    if (existsSync(path)) {
        return
    }
    const script = join(monorepoRoot, 'hub', 'scripts', 'download-tunwg.ts')
    if (!existsSync(script)) {
        throw new Error(`Missing tunwg binary (${path}) and download script ${script}`)
    }
    const proc = Bun.spawn([bunCommand, 'run', script], {
        cwd: monorepoRoot,
        stdout: 'pipe',
        stderr: 'pipe',
        env: process.env,
    })
    const [stdout, stderr, code] = await Promise.all([
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text(),
        proc.exited,
    ])
    if (code !== 0 || !existsSync(path)) {
        throw new Error(`download:tunwg failed: ${stderr || stdout}`)
    }
}

function requiredToolArchives(cliRoot: string, platform: string, arch: string): string[] {
    let platformDir: string
    if (platform === 'darwin') {
        platformDir = arch === 'arm64' ? 'arm64-darwin' : 'x64-darwin'
    } else if (platform === 'linux') {
        platformDir = arch === 'arm64' ? 'arm64-linux' : 'x64-linux'
    } else if (platform === 'win32') {
        platformDir = 'x64-win32'
    } else {
        throw new Error(`Unsupported platform: ${platform}`)
    }
    return [
        join(cliRoot, 'tools', 'archives', `difftastic-${platformDir}.tar.gz`),
        join(cliRoot, 'tools', 'archives', `ripgrep-${platformDir}.tar.gz`),
    ]
}

/**
 * Write empty embedded-web manifest so bun --compile does not pull stale
 * hashed web/dist imports from a previous generate:embedded-web-assets run.
 * Restores the previous file in finally.
 */
export function withStubEmbeddedAssets<T>(
    monorepoRoot: string,
    run: () => Promise<T>,
): Promise<T> {
    const manifestPath = join(monorepoRoot, 'hub', 'src', 'web', 'embeddedAssets.generated.ts')
    // Unique backup per call so overlapping builds cannot clobber each other's restore.
    const backupPath = `${manifestPath}.fleet-upgrade.${process.pid}.${Date.now()}.${Math.random().toString(16).slice(2)}.bak`
    const hadOriginal = existsSync(manifestPath)
    if (hadOriginal) {
        copyFileSync(manifestPath, backupPath)
    }
    writeFileSync(manifestPath, STUB_EMBEDDED_ASSETS, 'utf8')

    const restore = (): void => {
        try {
            if (hadOriginal && existsSync(backupPath)) {
                renameSync(backupPath, manifestPath)
            } else if (!hadOriginal && existsSync(manifestPath)) {
                unlinkSync(manifestPath)
            }
        } catch {
            // best-effort restore
        }
        try {
            if (existsSync(backupPath)) {
                unlinkSync(backupPath)
            }
        } catch {
            // ignore
        }
    }

    return run().finally(restore)
}

/** Serialize artifact compiles — concurrent heartbeats must not race the stub/restore. */
let artifactBuildLock: Promise<void> = Promise.resolve()

async function withArtifactBuildLock<T>(run: () => Promise<T>): Promise<T> {
    const previous = artifactBuildLock
    let release!: () => void
    artifactBuildLock = new Promise<void>((resolve) => {
        release = resolve
    })
    await previous
    try {
        return await run()
    } finally {
        release()
    }
}

/**
 * Ensure a compiled CLI artifact exists for platform/arch.
 * Uses the same bootstrap entry as `cli/scripts/build-executable.ts` (without
 * embedded web assets) so remotes get a runnable runner binary.
 */
export async function ensureCliArtifact(options: {
    version: string
    platform: string
    arch: string
    dataDir?: string
    hubPackageRoot?: string
    bunCommand?: string
}): Promise<ArtifactMeta> {
    const existing = readArtifactMeta(options.version, options.platform, options.arch, options.dataDir)
    if (existing && existsSync(existing.path)) {
        return existing
    }

    return await withArtifactBuildLock(async () => {
        // Re-check after waiting — another build may have finished.
        const cached = readArtifactMeta(options.version, options.platform, options.arch, options.dataDir)
        if (cached && existsSync(cached.path)) {
            return cached
        }

        if (options.platform !== process.platform || options.arch !== process.arch) {
            throw new Error(
                `Cross-compile not supported yet (hub is ${process.platform}/${process.arch}, requested ${options.platform}/${options.arch})`,
            )
        }

        const hubRoot = options.hubPackageRoot ?? defaultHubPackageRoot()
        const monorepo = findMonorepoRoot(hubRoot)
        if (!monorepo) {
            throw new Error('No monorepo root found; cannot build hub-artifact')
        }

        const cliRoot = join(monorepo, 'cli')
        const entry = join(cliRoot, 'src', 'bootstrap.ts')
        if (!existsSync(entry)) {
            throw new Error(`CLI bootstrap missing: ${entry}`)
        }

        for (const archive of requiredToolArchives(cliRoot, options.platform, options.arch)) {
            if (!existsSync(archive)) {
                throw new Error(`Missing tool archive for compile: ${archive}`)
            }
        }

        const bun = options.bunCommand
            ?? (process.execPath.includes('bun') ? process.execPath : 'bun')
        await ensureTunwgBinary(monorepo, options.platform, options.arch, bun)

        const dir = artifactsRoot(options.dataDir)
        mkdirSync(dir, { recursive: true })
        const outPath = join(dir, artifactFileName(options.version, options.platform, options.arch))
        const target = bunCompileTarget(options.platform, options.arch)
        const feature = featureFlagFor(options.platform, options.arch)

        await withStubEmbeddedAssets(monorepo, async () => {
            const proc = Bun.spawn([
                bun,
                'build',
                '--compile',
                '--no-compile-autoload-dotenv',
                `--feature=${feature}`,
                `--target=${target}`,
                `--outfile=${outPath}`,
                entry,
            ], {
                cwd: cliRoot,
                stdout: 'pipe',
                stderr: 'pipe',
                env: process.env,
            })
            const [stdout, stderr, code] = await Promise.all([
                new Response(proc.stdout).text(),
                new Response(proc.stderr).text(),
                proc.exited,
            ])
            if (code !== 0 || !existsSync(outPath)) {
                throw new Error(`bun compile failed: ${stderr || stdout}`)
            }
        })

        const buf = readFileSync(outPath)
        const sha256 = createHash('sha256').update(buf).digest('hex')
        const meta: ArtifactMeta = {
            version: options.version,
            platform: options.platform,
            arch: options.arch,
            path: outPath,
            sha256,
            sizeBytes: statSync(outPath).size,
        }
        writeMeta(meta)
        return meta
    })
}
