import type { EndpointDoc, EndpointQueryParamDoc } from './endpointCatalog'
import type { SchemaDoc, SchemaGroup } from './schemaCatalog'

export const GENERATED_HEADER = '<!-- AUTO-GENERATED by scripts/generate-plugin-api-docs.ts. DO NOT EDIT. -->\n\n'

export type JsonSchema = Record<string, unknown>

export type SchemaRenderInput = {
    doc: SchemaDoc
    jsonSchema: JsonSchema
    publicPath: string
}

const groupLabels: Record<SchemaGroup, string> = {
    manifest: 'Manifest',
    admin: 'Admin API',
    runtime: 'Hub runtime',
    runner: 'Runner runtime',
    agent: 'Agent extensions',
    web: 'Web descriptors',
    state: 'State files',
    marketplace: 'Marketplace'
}

export function schemaPublicPath(id: string): string {
    return `/plugin-api/schemas/${id}.schema.json`
}

function markdownSchemaLink(doc: SchemaDoc): string {
    return `[${doc.title}](${schemaPublicPath(doc.id)})`
}

function escapeTableCell(value: string): string {
    return value
        .replace(/\|/g, '\\|')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/\n/g, '<br>')
}

function queryParams(endpoint: EndpointDoc): EndpointQueryParamDoc[] {
    return [
        ...(endpoint.targetQuery ? [{ name: 'target', description: 'Plugin target scope.', schemaRef: 'PluginTargetScope' }] : []),
        ...(endpoint.queryParams ?? [])
    ]
}

function queryNames(endpoint: EndpointDoc): string {
    const names = queryParams(endpoint).map((entry) => `\`${entry.name}\``)
    return names.length > 0 ? names.join(', ') : '—'
}

export function renderAdminApiPage(endpoints: EndpointDoc[]): string {
    const rows = endpoints.map((endpoint) => {
        const body = endpoint.bodySchema ? `\`${endpoint.bodySchema}\`` : '—'
        return `| \`${endpoint.method}\` | \`${endpoint.path}\` | ${queryNames(endpoint)} | ${body} | \`${endpoint.responseSchema}\` | ${endpoint.description} |`
    })
    return GENERATED_HEADER + [
        '# Plugin admin API',
        '',
        'Authenticated HAPI Web API endpoints for plugin management. This page is generated from `scripts/plugin-api-docs/endpointCatalog.ts`.',
        '',
        'OpenAPI JSON: [/plugin-api/openapi.json](/plugin-api/openapi.json)',
        '',
        '| Method | Path | Query | Body | Response | Notes |',
        '|---|---|---|---|---|---|',
        ...rows,
        '',
        '## Target semantics',
        '',
        '- `hub`: operate on the Hub process and Hub-local plugin directory. Hub-local inventory, marketplace installed-state reads, and mutations are restricted to the default namespace token.',
        '- `runner:<machineId>`: operate through target-scoped Runner RPC; Hub does not read or write Runner plugin files directly.',
        '- `all-runners`: fan out supported operations to all Runner machines in the namespace.'
    ].join('\n')
}

export function renderSchemasIndex(inputs: SchemaRenderInput[]): string {
    const groups = [...new Set(inputs.map((input) => input.doc.group))]
    const sections = groups.map((group) => {
        const rows = inputs
            .filter((input) => input.doc.group === group)
            .map((input) => `| ${markdownSchemaLink(input.doc)} | ${escapeTableCell(input.doc.description)} |`)

        return [
            `## ${groupLabels[group]}`,
            '',
            '| Schema | Description |',
            '|---|---|',
            ...rows,
            ''
        ].join('\n')
    })

    return GENERATED_HEADER + [
        '# Plugin API schemas',
        '',
        'Machine-readable JSON Schemas generated from Zod schemas under `shared/src/plugins/*`.',
        '',
        'These schemas are the public contract. Human-oriented tutorials are intentionally hand-written and short.',
        '',
        ...sections
    ].join('\n')
}
