// This file is auto-generated by scripts/get-version.ts
// Do not edit manually
export default {
  "sha": "1c35ba4c3f56d2227213b282d6950770dc61484a",
  "shortSha": "1c35ba4",
  "branch": "main",
  "isDirty": true,
  "gitDescribe": "1c35ba4-dirty",
  "commitTime": "2026-02-05T12:09:38+01:00",
  "buildTime": "2026-02-05T18:24:36.214Z"
}
