#!/usr/bin/env bun

/**
 * Generates a static embedded assets file for a specific target platform
 * This avoids runtime dependency on bun:bundle module
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

interface Target {
    platform: string;
    arch: string;
    feature: string;
}

function parseTarget(target: string): Target {
    const parts = target.split('-');
    if (parts.length !== 3 || parts[0] !== 'bun') {
        throw new Error(`Invalid target: ${target}`);
    }

    const platform = parts[1] === 'windows' ? 'win32' : parts[1];
    const arch = parts[2];
    const platformToken = parts[1].toUpperCase();
    const feature = `HAPI_TARGET_${platformToken}_${arch.toUpperCase()}`;

    return { platform, arch, feature };
}

function getPlatformAssets(target: Target): string {
    const platformKey = `${target.platform}-${target.arch}`;

    const assetImports: Record<string, string[]> = {
        'darwin-arm64': [
            "import difftasticArm64Darwin from '../../tools/archives/difftastic-arm64-darwin.tar.gz' assert { type: 'file' };",
            "import ripgrepArm64Darwin from '../../tools/archives/ripgrep-arm64-darwin.tar.gz' assert { type: 'file' };"
        ],
        'darwin-x64': [
            "import difftasticX64Darwin from '../../tools/archives/difftastic-x64-darwin.tar.gz' assert { type: 'file' };",
            "import ripgrepX64Darwin from '../../tools/archives/ripgrep-x64-darwin.tar.gz' assert { type: 'file' };"
        ],
        'linux-arm64': [
            "import difftasticArm64Linux from '../../tools/archives/difftastic-arm64-linux.tar.gz' assert { type: 'file' };",
            "import ripgrepArm64Linux from '../../tools/archives/ripgrep-arm64-linux.tar.gz' assert { type: 'file' };"
        ],
        'linux-x64': [
            "import difftasticX64Linux from '../../tools/archives/difftastic-x64-linux.tar.gz' assert { type: 'file' };",
            "import ripgrepX64Linux from '../../tools/archives/ripgrep-x64-linux.tar.gz' assert { type: 'file' };"
        ],
        'win32-x64': [
            "import difftasticX64Win32 from '../../tools/archives/difftastic-x64-win32.tar.gz' assert { type: 'file' };",
            "import ripgrepX64Win32 from '../../tools/archives/ripgrep-x64-win32.tar.gz' assert { type: 'file' };"
        ]
    };

    const assetArrays: Record<string, string[]> = {
        'darwin-arm64': [
            "asset('tools/archives/difftastic-arm64-darwin.tar.gz', difftasticArm64Darwin)",
            "asset('tools/archives/ripgrep-arm64-darwin.tar.gz', ripgrepArm64Darwin)"
        ],
        'darwin-x64': [
            "asset('tools/archives/difftastic-x64-darwin.tar.gz', difftasticX64Darwin)",
            "asset('tools/archives/ripgrep-x64-darwin.tar.gz', ripgrepX64Darwin)"
        ],
        'linux-arm64': [
            "asset('tools/archives/difftastic-arm64-linux.tar.gz', difftasticArm64Linux)",
            "asset('tools/archives/ripgrep-arm64-linux.tar.gz', ripgrepArm64Linux)"
        ],
        'linux-x64': [
            "asset('tools/archives/difftastic-x64-linux.tar.gz', difftasticX64Linux)",
            "asset('tools/archives/ripgrep-x64-linux.tar.gz', ripgrepX64Linux)"
        ],
        'win32-x64': [
            "asset('tools/archives/difftastic-x64-win32.tar.gz', difftasticX64Win32)",
            "asset('tools/archives/ripgrep-x64-win32.tar.gz', ripgrepX64Win32)"
        ]
    };

    const imports = assetImports[platformKey];
    const assets = assetArrays[platformKey];

    if (!imports || !assets) {
        throw new Error(`Unsupported platform: ${platformKey}`);
    }

    return imports.join('\n') + '\n\n' +
        'const PLATFORM_ASSETS: EmbeddedAsset[] = [\n    ' +
        assets.join(',\n    ') +
        '\n];';
}

function generateCompiledAssets(target: string): string {
    const parsedTarget = parseTarget(target);
    const platformAssets = getPlatformAssets(parsedTarget);

    return `// This file is auto-generated by scripts/generate-compiled-assets.ts
// DO NOT EDIT MANUALLY
// Target: ${target}

import difftasticArchiveLicense from '../../tools/archives/difftastic-LICENSE' assert { type: 'file' };
import ripgrepArchiveLicense from '../../tools/archives/ripgrep-LICENSE' assert { type: 'file' };
import difftasticLicense from '../../tools/licenses/difftastic-LICENSE' assert { type: 'file' };
import ripgrepLicense from '../../tools/licenses/ripgrep-LICENSE' assert { type: 'file' };

${platformAssets}

export interface EmbeddedAsset {
    relativePath: string;
    sourcePath: string;
}

function asset(relativePath: string, sourcePath: string): EmbeddedAsset {
    return {
        relativePath,
        sourcePath
    };
}

const COMMON_ASSETS: EmbeddedAsset[] = [
    asset('tools/archives/difftastic-LICENSE', difftasticArchiveLicense),
    asset('tools/archives/ripgrep-LICENSE', ripgrepArchiveLicense),
    asset('tools/licenses/difftastic-LICENSE', difftasticLicense),
    asset('tools/licenses/ripgrep-LICENSE', ripgrepLicense)
];

export async function loadEmbeddedAssets(): Promise<EmbeddedAsset[]> {
    return [
        ...COMMON_ASSETS,
        ...PLATFORM_ASSETS
    ];
}
`;
}

async function main(): Promise<void> {
    const args = process.argv.slice(2);
    const target = args[0];

    if (!target) {
        console.error('Usage: bun run scripts/generate-compiled-assets.ts <target>');
        console.error('Example: bun run scripts/generate-compiled-assets.ts bun-linux-arm64');
        process.exit(1);
    }

    const scriptDir = dirname(fileURLToPath(import.meta.url));
    const projectRoot = join(scriptDir, '..');
    const outputPath = join(projectRoot, 'src', 'runtime', 'embeddedAssets.compiled.ts');

    const content = generateCompiledAssets(target);
    writeFileSync(outputPath, content, 'utf-8');

    console.log(`[generate-compiled-assets] Generated ${outputPath} for target ${target}`);
}

main().catch((error) => {
    console.error(`[generate-compiled-assets] ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
});
