/**
 * HAPI MCP STDIO Bridge
 *
 * Minimal STDIO MCP server exposing HAPI MCP tools.
 * On invocation it forwards the tool call to an existing HAPI HTTP MCP server
 * using the StreamableHTTPClientTransport.
 *
 * Configure the target HTTP MCP URL via env var `HAPI_HTTP_MCP_URL` or
 * via CLI flag `--url <http://127.0.0.1:PORT>`.
 *
 * Note: This process must not print to stdout as it would break MCP STDIO.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {
  clearGoalInputSchema,
  changeTitleInputSchema,
  getGoalInputSchema,
  sendAttachmentInputSchema,
  setGoalInputSchema
} from '@/claude/utils/hapiMcpTools';

type HapiBridgeToolName = 'change_title' | 'send_attachment' | 'get_goal' | 'set_goal' | 'clear_goal';

type HapiBridgeServer = {
  registerTool: (...args: any[]) => void;
};

type HapiBridgeHttpClient = {
  callTool(request: { name: string; arguments: Record<string, unknown> }): Promise<any>;
};

function parseArgs(argv: string[]): { url: string | null; includeGoalTools: boolean } {
  let url: string | null = null;
  let includeGoalTools = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--url' && i + 1 < argv.length) {
      url = argv[i + 1];
      i++;
    } else if (a === '--goal-tools') {
      includeGoalTools = true;
    }
  }
  return { url, includeGoalTools };
}

function getBridgeToolErrorPrefix(toolName: HapiBridgeToolName): string {
  switch (toolName) {
    case 'change_title':
      return 'Failed to change chat title';
    case 'send_attachment':
      return 'Failed to send attachment';
    case 'get_goal':
      return 'Failed to get goal';
    case 'set_goal':
      return 'Failed to set goal';
    case 'clear_goal':
      return 'Failed to clear goal';
  }
}

export function registerHapiBridgeTools(
  server: HapiBridgeServer,
  ensureHttpClient: () => Promise<HapiBridgeHttpClient>,
  options: { includeGoalTools?: boolean } = {}
): void {
  const tools: Array<{
    name: HapiBridgeToolName;
    description: string;
    title: string;
    inputSchema: unknown;
  }> = [
    {
      name: 'change_title',
      description: 'Change the title of the current chat session',
      title: 'Change Chat Title',
      inputSchema: changeTitleInputSchema,
    },
    {
      name: 'send_attachment',
      description: [
        'Send files generated by the agent to the user as HAPI chat attachments.',
        'Use only for final user-facing artifacts that the user asked to receive.',
        'Each file path must be inside the current session working directory.'
      ].join(' '),
      title: 'Send Attachment',
      inputSchema: sendAttachmentInputSchema,
    },
  ];

  if (options.includeGoalTools) {
    tools.push(
      {
        name: 'get_goal',
        description: 'Get the current HAPI/Codex conversation goal for this thread.',
        title: 'Get Goal',
        inputSchema: getGoalInputSchema,
      },
      {
        name: 'set_goal',
        description: [
          'Set or replace the current HAPI/Codex conversation goal for this thread.',
          'Use this instead of native create_goal when creating or replacing a goal.'
        ].join(' '),
        title: 'Set Goal',
        inputSchema: setGoalInputSchema,
      },
      {
        name: 'clear_goal',
        description: 'Clear the current HAPI/Codex conversation goal for this thread.',
        title: 'Clear Goal',
        inputSchema: clearGoalInputSchema,
      }
    );
  }

  for (const tool of tools) {
    server.registerTool(
      tool.name,
      {
        description: tool.description,
        title: tool.title,
        inputSchema: tool.inputSchema,
      },
      async (args: Record<string, unknown>) => {
        try {
          const client = await ensureHttpClient();
          const response = await client.callTool({ name: tool.name, arguments: args });
          // Pass-through response from HTTP server
          return response as any;
        } catch (error) {
          return {
            content: [
              { type: 'text' as const, text: `${getBridgeToolErrorPrefix(tool.name)}: ${error instanceof Error ? error.message : String(error)}` },
            ],
            isError: true,
          };
        }
      }
    );
  }
}

export async function runHappyMcpStdioBridge(argv: string[]): Promise<void> {
  try {
    // Resolve target HTTP MCP URL
    const { url: urlFromArgs, includeGoalTools } = parseArgs(argv);
    const baseUrl = urlFromArgs || process.env.HAPI_HTTP_MCP_URL || '';

    if (!baseUrl) {
      // Write to stderr; never stdout.
      process.stderr.write(
        '[hapi-mcp] Missing target URL. Set HAPI_HTTP_MCP_URL or pass --url <http://127.0.0.1:PORT>\n'
      );
      process.exit(2);
    }

    let httpClient: Client | null = null;

    async function ensureHttpClient(): Promise<Client> {
      if (httpClient) return httpClient;
      const client = new Client(
        { name: 'hapi-stdio-bridge', version: '1.0.0' },
        { capabilities: {} }
      );

      const transport = new StreamableHTTPClientTransport(new URL(baseUrl));
      await client.connect(transport);
      httpClient = client;
      return client;
    }

    // Create STDIO MCP server
    const server = new McpServer({
      name: 'HAPI MCP Bridge',
      version: '1.0.0',
    });

    registerHapiBridgeTools(server, ensureHttpClient, { includeGoalTools });

    // Start STDIO transport
    const stdio = new StdioServerTransport();
    await server.connect(stdio);
  } catch (err) {
    try {
      process.stderr.write(`[hapi-mcp] Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
    } finally {
      process.exit(1);
    }
  }
}
