export const RPC_METHODS = {
    Permission: 'permission',
    Abort: 'abort',
    Switch: 'switch',
    SetSessionConfig: 'set-session-config',
    KillSession: 'killSession',
    HandoffLocal: 'handoff-local',
    SpawnHappySession: 'spawn-happy-session',
    StopSession: 'stop-session',
    StopRunner: 'stop-runner',
    ListMachineDirectory: 'list-directory',
    PathExists: 'path-exists',
    CursorChatStoreStatus: 'cursor-chat-store-status',
    GitStatus: 'git-status',
    GitDiffNumstat: 'git-diff-numstat',
    GitDiffFile: 'git-diff-file',
    ReadFile: 'readFile',
    ReadGeneratedImage: 'readGeneratedImage',
    WriteFile: 'writeFile',
    ListDirectory: 'listDirectory',
    GetDirectoryTree: 'getDirectoryTree',
    UploadFile: 'uploadFile',
    DeleteUpload: 'deleteUpload',
    Ripgrep: 'ripgrep',
    Difftastic: 'difftastic',
    Bash: 'bash',
    ListSlashCommands: 'listSlashCommands',
    ListSkills: 'listSkills',
    ListCodexModels: 'listCodexModels',
    ListCodexSessions: 'listCodexSessions',
    ArchiveCodexSession: 'archiveCodexSession',
    ListCursorModels: 'listCursorModels',
    ListPiModels: 'listPiModels',
    ListOmpModels: 'listOmpModels',
    ListOpencodeModels: 'listOpencodeModels',
    ListOpencodeModelsForCwd: 'listOpencodeModelsForCwd',
    ListGrokModelsForCwd: 'listGrokModelsForCwd',
    ListGrokModels: 'listGrokModels',
    ListGrokReasoningEffortOptions: 'listGrokReasoningEffortOptions',
    ListOpencodeReasoningEffortOptions: 'listOpencodeReasoningEffortOptions',
    // OMP superset RPCs (hapi → OMP, single-direction). OMP shares Pi's RPC
    // protocol family but exposes extra commands; these surface the load-bearing
    // ones (compaction, steering/interrupt modes, model/thinking cycling,
    // session stats) to the hub/web.
    OmpCompact: 'omp-compact',
    OmpSetSteeringMode: 'omp-set-steering-mode',
    OmpSetInterruptMode: 'omp-set-interrupt-mode',
    OmpSetFollowUpMode: 'omp-set-follow-up-mode',
    OmpCycleModel: 'omp-cycle-model',
    OmpCycleThinkingLevel: 'omp-cycle-thinking-level',
    OmpGetSessionStats: 'omp-get-session-stats'
} as const

export type RpcMethod = typeof RPC_METHODS[keyof typeof RPC_METHODS]
