export const RPC_METHODS = {
    Permission: 'permission',
    Abort: 'abort',
    Switch: 'switch',
    SetSessionConfig: 'set-session-config',
    KillSession: 'killSession',
    HandoffLocal: 'handoff-local',
    SpawnHappySession: 'spawn-happy-session',
    StopSession: 'stop-session',
    StopRunner: 'stop-runner',
    ListMachineDirectory: 'list-directory',
    PathExists: 'path-exists',
    GitStatus: 'git-status',
    GitDiffNumstat: 'git-diff-numstat',
    GitDiffFile: 'git-diff-file',
    ReadFile: 'readFile',
    ReadGeneratedImage: 'readGeneratedImage',
    WriteFile: 'writeFile',
    ListDirectory: 'listDirectory',
    GetDirectoryTree: 'getDirectoryTree',
    UploadFile: 'uploadFile',
    DeleteUpload: 'deleteUpload',
    Ripgrep: 'ripgrep',
    Difftastic: 'difftastic',
    Bash: 'bash',
    ListSlashCommands: 'listSlashCommands',
    ListSkills: 'listSkills',
    ListCodexModels: 'listCodexModels',
    ListOpencodeModels: 'listOpencodeModels',
    ListOpencodeModelsForCwd: 'listOpencodeModelsForCwd',
    RunnerPluginsList: 'runner.plugins.list',
    RunnerPluginsInspect: 'runner.plugins.inspect',
    RunnerPluginsEnable: 'runner.plugins.enable',
    RunnerPluginsDisable: 'runner.plugins.disable',
    RunnerPluginsConfigUpdate: 'runner.plugins.config.update',
    RunnerPluginsReload: 'runner.plugins.reload',
    RunnerPluginsInstallPrepare: 'runner.plugins.install.prepare',
    RunnerPluginsInstallCommit: 'runner.plugins.install.commit',
    RunnerPluginsLocalDirectory: 'runner.plugins.local-directory',
    RunnerPluginsInstallLocal: 'runner.plugins.install-local',
    RunnerPluginsInstallPackage: 'runner.plugins.install-package',
    RunnerPluginsDelete: 'runner.plugins.delete',
    RunnerPluginActionInvoke: 'runner.plugins.action.invoke',
    RunnerSpawnOptionsPreview: 'runner.spawn-options.preview',
    RunnerAgentHistoryImport: 'runner.agent.history.import'
} as const

export type RpcMethod = typeof RPC_METHODS[keyof typeof RPC_METHODS]
