// This file is auto-generated by scripts/get-version.ts
// Do not edit manually
export default {
  "sha": "dee3b9f32198ae4bfc1dc063d4f6692d6e611856",
  "shortSha": "dee3b9f",
  "branch": "main",
  "isDirty": true,
  "gitDescribe": "dee3b9f-dirty",
  "commitTime": "2026-02-05T19:29:35+01:00",
  "buildTime": "2026-02-05T18:36:45.685Z"
}
